# Generated by Django 4.2.15 on 2024-08-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_val', models.JSONField(default=list)),
                ('forecast_data', models.JSONField(default=list)),
            ],
        ),
    ]
